apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
#  type: NodePort
  type: LoadBalancer
  selector:
    app: ui-pod
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 4200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-pod
  template:
    metadata:
      labels:
        app: ui-pod
    spec:
      containers:
      - name: ui-container
        image: intersystemsdc/irisdemo-demo-htap:ui-version-2.5.2
        resources:
          requests:
              cpu: 0.5
              memory: 512M
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: htapmaster
spec:
  selector:
    app: master-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
  labels:
    app: master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-pod
  template:
    metadata:
      labels:
        app: master-pod
    spec:
      containers:
      - name: master-container
        image: intersystemsdc/irisdemo-demo-htap:master-version-2.5.2
        resources:
          requests:
              cpu: 0.5
              memory: 512M
        ports:
        - containerPort: 8080
        env:
        - name: MASTER_SPEEDTEST_TITLE
          value: "SpeedTest | IRIS Community 2020.3.0.200.0"
        - name: START_CONSUMERS
          value: "true"
        - name: DISABLE_JOURNAL_FOR_DROP_TABLE
          value: "true"
        - name: DISABLE_JOURNAL_FOR_TRUNCATE_TABLE
          value: "true"
        - name: INGESTION_THREADS_PER_WORKER
          value: "2"
        - name: INGESTION_BATCH_SIZE
          value: "1000"
        - name: INGESTION_JDBC_URL
          value: "jdbc:IRIS://htapirisdb:1972/USER"
        - name: INGESTION_JDBC_USERNAME
          value: "SuperUser"
        - name: INGESTION_JDBC_PASSWORD
          value: "sys"
        - name: CONSUMER_JDBC_URL
          value: "jdbc:IRIS://htapirisdb:1972/USER"
        - name: CONSUMER_JDBC_USERNAME
          value: "SuperUser"
        - name: CONSUMER_JDBC_PASSWORD
          value: "sys"
        - name: CONSUMER_THREADS_PER_WORKER
          value: "1"
        - name: CONSUMER_TIME_BETWEEN_QUERIES_IN_MILLIS
          value: "0"
        - name: DATABASE_SIZE_IN_GB
          value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-worker-deployment
  labels:
    app: ingestion-worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingestion-worker-pod
  template:
    metadata:
      labels:
        app: ingestion-worker-pod
    spec:
      containers:
      - name: ingestion-worker-container
        image: intersystemsdc/irisdemo-demo-htap:iris-jdbc-ingest-worker-version-2.5.2
        resources:
          requests:
              cpu: 0.5
              memory: 512M
        ports:
        - containerPort: 8080
        env:
        - name: MASTER_HOSTNAME
          value: "htapmaster"
        - name: MASTER_PORT
          value: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-worker-deployment
  labels:
    app: query-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-worker-pod
  template:
    metadata:
      labels:
        app: query-worker-pod
    spec:
      containers:
      - name: query-worker-container
        image: intersystemsdc/irisdemo-demo-htap:iris-jdbc-query-worker-version-2.5.2
        resources:
          requests:
              cpu: 0.5
              memory: 512M

        ports:
        - containerPort: 8080
        env:
        - name: MASTER_HOSTNAME
          value: "htapmaster"
        - name: MASTER_PORT
          value: "8080"  
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: htapui-ingress
spec:
  backend:
    serviceName: ui
    servicePort: 10000