apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-pod
  template:
    metadata:
      labels:
        app: ui-pod
    spec:
      containers:
      - name: ui-container
        image: intersystemsdc/irisdemo-demo-htap:ui-version-2.5.2
        resources:
          requests:
              cpu: 0.5
              memory: 512M
        ports:
        - containerPort: 4200
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-label"
                operator: In
                values:
                - "htap"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: "app"
                  operator: "In"
                  values:
                  - "master-pod"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: "app"
                  operator: "In"
                  values:
                  - "ui-pod"
                  - "ingestion-worker-pod"
                  - "query-worker-pod"
  