apiVersion: v1
kind: PersistentVolume
metadata:
  name: iris-pv
  labels:
    type: local
spec:
  storageClassName: local-storage-class
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/local/var/irisdata"
