apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
#  type: NodePort
  type: LoadBalancer
  selector:
    app: ui-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: ui-ingress
# spec:
#   backend:
#     serviceName: ui
#     servicePort: 80



